name: flutter_smartbawangv2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  context_menus: ^1.0.2
  dson: ^2.0.0
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_verification_code: ^1.1.7
  gif: ^2.3.0
  go_router: ^14.1.2
  google_fonts: 6.1.0
  image_picker: ^1.0.8
  path: ^1.8.3
  path_provider: ^2.1.3
  provider: ^6.1.2
  sqflite: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
